#!/usr/bin/env ruby
class Tasks < Morpheus::Base
  # rspec ruby_versions: %w(1.9.2 ree)
  # rdoc  title: 'Morpheus - Task Framework'
  # rcov
  # cucumber format: :progress, ruby_versions: %w(1.9.2 ree)
end

:morpheus.tasks do
end